# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
title: eni6ma.com
description: Corporate site for eni6ma.com.
url: "https://eni6ma.com"
author: eni6ma


# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information

author-bio: Creators of Cybernetic Cryptography  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
  - text: About
    permalink: about
  - text: Cryptography
    permalink: cryptography
  - text: Blog
    permalink: blog
  - text: Features
    permalink: features
  - text: Agentic AI
    permalink: agentic
  - text: Security
    permalink: security
  - text: Integrations
    permalink: integrations
  - text: UseCases
    permalink: use-cases
  - text: Technology
    permalink: technology
  - text: FAQ
    permalink: faq

# use false to turn off any social media links
twitter: https://x.com/
youtube: https://youtube.com/
github: https://github.com/
linkedin: https://linkedin.com/
medium: false
google-scholar: false
email: mailto:contact@eni6ma.co

# footer information
footer-msg: "Powered by Eni6ma"
footer-msg-link: https://github.com/eni6ma

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
